apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-celery-flower-deployment
  namespace: default
  labels:
    app: django-celery-flower
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: django-celery-flower
  template:
    metadata:
      labels:
        app: django-celery-flower
    spec:
      terminationGracePeriodSeconds: 3800
      containers:
        - name: django-celery-flower
          image: bibekkhatri/django-celery-keda-example:1.0.0
          command: ["celery", "-A", "core", "flower", "--port=5555"]
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "500m"
              memory: "500M"
            limits:
              cpu: "500m"
              memory: "5000M"
          ports:
            - containerPort: 5555
          readinessProbe:
            httpGet:
              path: /
              port: 5555
            initialDelaySeconds: 30
            periodSeconds: 20
          livenessProbe:
            httpGet:
              path: /
              port: 5555
            initialDelaySeconds: 15
            periodSeconds: 120
          env:
            - name: CELERY_BROKER_URL
              valueFrom:
                secretKeyRef:
                  name: django
                  key: celery-broker-url
                  optional: false

---
apiVersion: v1
kind: Service
metadata:
  name: django-celery-flower-load-balancer
spec:
  selector:
    app: django-celery-flower
  ports:
    - port: 5555
      name: http
      targetPort: 5555
  type: LoadBalancer
