apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: django-celery-worker-deployment
spec:
  scaleTargetRef:
    name: django-celery-worker-deployment
  minReplicaCount: 1
  maxReplicaCount: 5
  triggers:
    - type: rabbitmq
      metadata:
        queueName: celery
        queueLength: "5"
      authenticationRef:
        name: celery-queue-trigger
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: celery-queue-trigger
  namespace: default
spec:
  secretTargetRef:
    - parameter: host
      name: django
      key: celery-broker-url
---

